# Generated by Django 4.2.13 on 2024-05-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_category', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='category',
            field=models.ManyToManyField(default=None, to='task_category.categorymodel'),
        ),
    ]
